In [1]:
import numpy as np

In [10]:
(np.random.dirichlet([.3, .2, .3])*100).astype(int)

array([10,  9, 80])

In [11]:
(np.random.multivariate_normal([.3, .2, .3])*100).astype(int)

TypeError: multivariate_normal() takes at least 2 positional arguments (1 given)

In [24]:
(np.random.multivariate_normal(
    [.6, .4],
    [
        [1, .5], 
        [.5, 1]
    ]
)*100).astype(int)

array([86,  7])

In [43]:
mg = [.2, .8]
fe = [.1, .5]
al = [.1, .4]

e = [mg, fe, al]

e

[[0.2, 0.8], [0.1, 0.5], [0.1, 0.4]]

In [46]:
base = sum([i[0] for i in e])
remainder = 1 - base
base, remainder

(0.4, 0.6)

In [47]:
er = [j-i for i,j in e]
er

[0.6000000000000001, 0.4, 0.30000000000000004]

In [98]:
n = 10000
epsilon = .0001

v = np.hstack([
    np.random.uniform(0, .6, (n, 1)),
    np.random.uniform(0, .4, (n, 1)),
    np.random.uniform(0, .3, (n, 1))
])

while True:
    s = v.sum(axis=1, keepdims=True)
    v = (v/s)*remainder
    mask = v < er
    r = np.clip(v - er, 0, None)
    v = v - r
    v = v + (mask * (r.sum(axis=1) / mask.sum(axis=1)).reshape(-1, 1))
    if np.abs(remainder - v.sum(axis=1)).mean() < epsilon:
        break
v

array([[0.24450094, 0.17015275, 0.18534631],
       [0.33787895, 0.11692832, 0.14519273],
       [0.22929236, 0.20644416, 0.16426348],
       ...,
       [0.27751172, 0.02248828, 0.3       ],
       [0.32244434, 0.23062245, 0.0469332 ],
       [0.21439032, 0.21158702, 0.17402266]])

In [114]:
np.random.randint(*[2, 3+1])

2

In [106]:
v[:,0].shape

(10000,)

In [90]:
v + (mask * (r.sum(axis=1) / mask.sum(axis=1)).reshape(-1, 1))

array([[0.43069037, 0.09908611, 0.07022352],
       [0.29549099, 0.14830941, 0.1561996 ],
       [0.32653339, 0.24128261, 0.032184  ],
       [0.3426094 , 0.21159262, 0.04579797],
       [0.42378799, 0.11202859, 0.06418341],
       [0.30886628, 0.09989651, 0.19123721],
       [0.09283066, 0.26901905, 0.23815029],
       [0.33134445, 0.11850587, 0.15014968],
       [0.24893436, 0.18932264, 0.16174301],
       [0.35564305, 0.21625167, 0.02810528],
       [0.23536117, 0.11414493, 0.2504939 ],
       [0.24402775, 0.13087225, 0.2251    ],
       [0.21505474, 0.25110487, 0.13384039],
       [0.40668408, 0.04653354, 0.14678238],
       [0.33223169, 0.24940953, 0.01835878],
       [0.09270287, 0.32792377, 0.17937335],
       [0.27163187, 0.16131453, 0.1670536 ],
       [0.2113283 , 0.27448236, 0.11418934],
       [0.28431523, 0.21047961, 0.10520516],
       [0.18631724, 0.22612023, 0.18756254],
       [0.27100078, 0.27734683, 0.05165239],
       [0.19629121, 0.15599418, 0.24771461],
       [0.

In [71]:
().max(axis=0)

array([0.51819469, 0.48531933, 0.4179453 ])

In [37]:
(np.random.dirichlet([.3/.3, .3/.3, .2/.3], 100)*.3).mean(axis=0)

array([0.10583389, 0.11619859, 0.07796751])

In [40]:
np.random.uniform(0, .3, 100).

array([0.13973045, 0.26175997, 0.03032623, 0.04334607, 0.06525919,
       0.05828494, 0.15684558, 0.021649  , 0.04540511, 0.01168353,
       0.20205348, 0.07783196, 0.19040343, 0.10650728, 0.23817727,
       0.29491684, 0.2668693 , 0.13887666, 0.20572537, 0.29497441,
       0.03350519, 0.19824205, 0.27870415, 0.19333929, 0.11400419,
       0.03994783, 0.19499268, 0.19896374, 0.07108705, 0.09150387,
       0.04527015, 0.04387614, 0.0868268 , 0.17954728, 0.22054238,
       0.22494754, 0.10226065, 0.17844594, 0.28563748, 0.04084861,
       0.00895984, 0.11356124, 0.04312995, 0.08703568, 0.22611631,
       0.06320879, 0.24092101, 0.18227995, 0.2042579 , 0.1938455 ,
       0.21587845, 0.2826496 , 0.25284241, 0.29577161, 0.13610027,
       0.10113323, 0.27908333, 0.00731766, 0.16869443, 0.18517493,
       0.06454272, 0.25596764, 0.25927574, 0.06367048, 0.0369488 ,
       0.02540027, 0.08120563, 0.11981771, 0.12403923, 0.25564978,
       0.17373492, 0.16514544, 0.09524488, 0.27445189, 0.20304

In [115]:
import periodictable

In [118]:
periodictable.formula("(SiO3)2").mass

152.1674

In [119]:
periodictable.formula("SiO3").mass

76.0837

In [120]:
import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from lib import get_standards_characteristics, load_target_minerals, get_formula, load_images

def get_variable_percent(formula, n, epsilon=.0001):
    elements = [
        {'element': e, 'min': m[0], 'max': m[1]}
        for e, m in formula.items()
    ]

    base = sum([e['min'] for e in elements])
    remainder = 1 - base
    element_remainders = [e['max'] - e['min'] for e in elements]

    v = np.hstack([
        np.random.uniform(0, e, (n, 1)) for e in element_remainders
    ])

    while remainder > 0:
        s = v.sum(axis=1, keepdims=True)
        v = (v/s)*remainder
        mask = v < element_remainders
        r = np.clip(v - element_remainders, 0, None)
        v = v - r
        v = v + (mask * (r.sum(axis=1) / mask.sum(axis=1)).reshape(-1, 1))
        if np.abs(remainder - v.sum(axis=1)).mean() < epsilon:
            break

    return [(e['element'], e['min']+v[:, i]) for i, e in enumerate(elements)]

def simulate_mineral(mineral, formula, standard_elements, n=5):
    if not isinstance(formula, list):
        formula = [formula]

    #elements = []
    #masses = []

    mineral_elements = {}
    def append(element, mass):
        if element in mineral_elements:
            mineral_elements[element] += mass
        else:
            mineral_elements[element] = mass

    for component in formula:
        if isinstance(component, str):
            for element, mass in get_formula(component, format="mass").items():
                append(element, np.ones(n)*mass)
        elif isinstance(component, dict):
            if 'quantity' in component:
                quantity = component['quantity']
                if isinstance(quantity, list):
                    quantity = np.random.randint(quantity[0], quantity[1]+1)
            else:
                quantity = 1

            for molecule, percent in get_variable_percent(component['components'], n):
                for element, mass in get_formula(molecule, format="mass").items():
                    append(element, percent*mass*quantity)
        else:
            raise ValueError(f"{str(component)} is not a recognized format")

    # Calculate mass percents
    df = pd.DataFrame(mineral_elements)
    df.columns = [f"{element}_mass" for element in df.columns]
    df['mass'] = df.sum(axis=1)
    for element in mineral_elements:
        df[f"{element}_percent"] = df[f"{element}_mass"]/df['mass']

    # Convert to intensities
    for element in standard_elements:
        e = standard_elements[element]
        df[element] = (
            e['intercept'] + np.random.normal(scale=e['intercept'], size=n)
        )

        if f"{element}_percent" in df:
            df[element] += (
                e['coef']*df[f"{element}_percent"] +
                np.random.normal(scale=e['std'], size=n)
            )

        df[element] = np.clip(df[element], 0, None)


    '''mineral_elements = get_formula(component)
    for element, weight in mineral_elements.items():
        elements.append(element)
        masses.append(np.ones(n)*weight)'''

    df['mineral'] = mineral
    #df['formula'] = formula

    #return elements, masses
    return df





ModuleNotFoundError: No module named 'lib'

In [ ]:
    characteristics = get_standards_characteristics(standards_dir, bits)
    target_minerals = load_target_minerals(target_minerals_file)
    #print(characteristics)
    elements = list(characteristics.keys())
    #

    mineral_dfs = []
    for mineral, formula in target_minerals.items():
        #print(mineral)

        df = simulate_mineral(mineral, formula, characteristics, 10000)
        #print(df.head())
        mineral_dfs.append(df[elements + ['mineral']])

    df = pd.concat(mineral_dfs)

    #print(len(df))
    #print(df.head())

    X = df[elements].values
    Y = df['mineral']
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.2)

    print("Training Classifier...")
    model = RandomForestClassifier(100, max_depth=10, n_jobs=-1)
    model.fit(X_train, Y_train)
    print("Training Accuracy:", (model.predict(X_train) == Y_train).mean())
    print("Testing Accuracy:", (model.predict(X_test) == Y_test).mean())

    meteorite_df, meteorite_shape = load_images(meteorite_dir, bits)
    x = meteorite_df[elements].values
    meteorite_df['mineral'] = model.predict(x)
    
    #print(meteorite_df.head(20))
    results = meteorite_df.merge(
        pd.Series(
            model.classes_, name='mineral'
        ).reset_index().rename(columns={'index': 'mineral_index'}),
        on='mineral'
    ).sort_values('order')

    figure, ax = plt.subplots(figsize=(30,30))
    i = ax.imshow(
        results['mineral_index'].values.reshape(meteorite_shape),
        cmap=plt.cm.get_cmap('jet', len(model.classes_))
    )
    cbar = figure.colorbar(i, ticks=range(len(model.classes_)))
    cbar.ax.set_yticklabels(model.classes_)
    ax.legend()

    #figure.savefig('test.png')